build: add npm config files

diff --git a/.github/workflows/Preprocessor.yml b/.github/workflows/Preprocessor.yml
--- a/.github/workflows/Preprocessor.yml
+++ b/.github/workflows/Preprocessor.yml
@@ -1,44 +1,58 @@
-name: "The fallen crown"
+name: Preprocessor
 
 on:
-  workflow_dispatch:
   push:
     branches: [ "main" ]
+    paths:
+      - '**/preprocessor.*'  # 'preprocessor' in any directory and all types
+      - 'sub/*.json'
   schedule:
-    - cron: '0 */3 * * *'
+    - cron: '0 */4 * * *'  # Runs every 4 hours
+  workflow_dispatch:  # Allow manual triggering of the workflow
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     defaults:
       run:
-        shell: bash -e {0}
+        shell: bash -e {0}  # Fail the job if any command fails
     steps:
+      # Step 1: Checkout the repository
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-        env:
-          NODE_VERSION: '20'
+          fetch-depth: 0  # Fetch full history
+          submodules: 'recursive'  # Include submodules
+          github_token: ${{ secrets.GITHUB_TOKEN }} 
 
+      # Step 2: Set up PHP
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '8.4'
+          php-version: '8.4'  # Use PHP 8.4
 
-      - name: Lets go sweetheart
-        run: php edge/The-fallen-crown.php
+      # Step 3: Run the preprocessor.php script
+      - name: Run preprocessor.php
+        run: php edge/preprocessor.php || exit 1
 
+      # Step 4: Configure Git
       - name: Configure Git
         run: |
-          git config --global user.name "github-actions"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "Diana-Cl"
+          git config --local user.email "135276904+Diana-Cl@users.noreply.github.com"
 
+      # Step 5: Commit changes if there are any
       - name: Commit changes with timestamp
         run: |
           git add -A
-          git diff --cached --quiet || git commit -m "ⅣⅭ $(TZ='Asia/Tehran' date '+%H:%M:%S')"
-          
+          if ! git diff --cached --quiet; then
+            git commit -m "ⅣⅭ Updated $(TZ='Asia/Tehran' date '+%H:%M:%S')" \
+                       -m "The list of Cloudflare IPs has been updated."
+          else
+            echo "No changes detected. Skipping commit."
+          fi
+
+      # Step 6: Push changes
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
